/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cute_pastries.glb --transform 
Files: public/models/cute_pastries.glb [1.33MB] > /home/gift/Documents/pastry shop/cute_pastries-transformed.glb [160.48KB] (88%)
Author: MiwhyMiwh (https://sketchfab.com/MiwhyMiwh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-pastries-4a51ea7a932240c092582717517e175d
Title: Cute pastries
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/cute_pastries-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="star" position={[-191.892, 545.544, 175.116]} rotation={[-2.305, 1.421, 0.745]} scale={28.828}>
            <mesh name="star_star_0" geometry={nodes.star_star_0.geometry} material={materials.star} />
          </group>
          <group name="dotted" position={[-191.892, 653.88, 316.397]} rotation={[-2.305, 1.421, 0.745]} scale={44.164}>
            <mesh name="dotted_dots_0" geometry={nodes.dotted_dots_0.geometry} material={materials.dots} />
          </group>
          <group name="star001" position={[-152.892, 625.689, -73.844]} rotation={[-2.305, 1.421, 0.745]} scale={28.828}>
            <mesh name="star001_star_0" geometry={nodes.star001_star_0.geometry} material={materials.star} />
          </group>
          <group name="dotted001" position={[-85.591, 640.422, -31.353]} rotation={[-2.305, 1.421, 0.745]} scale={44.164}>
            <mesh name="dotted001_dots_0" geometry={nodes.dotted001_dots_0.geometry} material={materials.dots} />
          </group>
          <group name="star002" position={[-157.366, 580.241, -291.75]} rotation={[-2.305, 1.421, 0.745]} scale={14.195}>
            <mesh name="star002_star_0" geometry={nodes.star002_star_0.geometry} material={materials.star} />
          </group>
          <group name="dotted002" position={[-104.004, 561.888, -362.766]} rotation={[-2.305, 1.421, 0.745]} scale={36.054}>
            <mesh name="dotted002_dots_0" geometry={nodes.dotted002_dots_0.geometry} material={materials.dots} />
          </group>
          <group name="star003" position={[-177.373, 632.711, -572.267]} rotation={[-2.305, 1.421, 0.745]} scale={14.195}>
            <mesh name="star003_star_0" geometry={nodes.star003_star_0.geometry} material={materials.star} />
          </group>
          <group name="dotted003" position={[-111.84, 575.136, -615.303]} rotation={[-2.305, 1.421, 0.745]} scale={36.054}>
            <mesh name="dotted003_dots_0" geometry={nodes.dotted003_dots_0.geometry} material={materials.dots} />
          </group>
          <group name="Cake_strawberry" position={[-303.239, 560.014, 343.906]} rotation={[-1.956, -0.21, 0.872]} scale={100}>
            <mesh name="Cake_strawberry_Cake_strawberry_0" geometry={nodes.Cake_strawberry_Cake_strawberry_0.geometry} material={materials.Cake_strawberry} />
            <mesh name="Cake_strawberry_Outline_0" geometry={nodes.Cake_strawberry_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Cake_strawberry001" position={[-340.352, 540.557, 320.616]} rotation={[-1.915, -0.162, 0.879]} scale={88.162}>
            <mesh name="Cake_strawberry001_Cake_strawberry_0" geometry={nodes.Cake_strawberry001_Cake_strawberry_0.geometry} material={materials.Cake_strawberry} />
            <mesh name="Cake_strawberry001_Outline_0" geometry={nodes.Cake_strawberry001_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Cake_strawberry002" position={[-271.29, 577.433, 371.706]} rotation={[-2.074, -0.341, 0.839]} scale={88.162}>
            <mesh name="Cake_strawberry002_Cake_strawberry_0" geometry={nodes.Cake_strawberry002_Cake_strawberry_0.geometry} material={materials.Cake_strawberry} />
            <mesh name="Cake_strawberry002_Outline_0" geometry={nodes.Cake_strawberry002_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Cake_strawberry003" position={[-338.073, 565.48, 380.864]} rotation={[-2.025, -0.152, 0.859]} scale={88.162}>
            <mesh name="Cake_strawberry003_Cake_strawberry_0" geometry={nodes.Cake_strawberry003_Cake_strawberry_0.geometry} material={materials.Cake_strawberry} />
            <mesh name="Cake_strawberry003_Outline_0" geometry={nodes.Cake_strawberry003_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Cake_strawberry004" position={[-265.11, 553.219, 309.241]} rotation={[-1.912, -0.245, 0.881]} scale={88.162}>
            <mesh name="Cake_strawberry004_Cake_strawberry_0" geometry={nodes.Cake_strawberry004_Cake_strawberry_0.geometry} material={materials.Cake_strawberry} />
            <mesh name="Cake_strawberry004_Outline_0" geometry={nodes.Cake_strawberry004_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Cake_strawberry005" position={[-301.433, 552.143, 347.094]} rotation={[-1.956, -0.21, 0.872]} scale={100}>
            <mesh name="Cake_strawberry005_Cake_strawberry_0" geometry={nodes.Cake_strawberry005_Cake_strawberry_0.geometry} material={materials.Cake_strawberry} />
            <mesh name="Cake_strawberry005_Outline_0" geometry={nodes.Cake_strawberry005_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Cupcake" position={[-201.638, 558.151, -33.266]} rotation={[-1.731, 0.229, 0.386]} scale={100}>
            <mesh name="Cupcake_Cupcake_0" geometry={nodes.Cupcake_Cupcake_0.geometry} material={materials.Cupcake} />
            <mesh name="Cupcake_Outline_0" geometry={nodes.Cupcake_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Cupcake001" position={[-201.638, 558.151, -33.266]} rotation={[-1.731, 0.229, 0.386]} scale={100}>
            <mesh name="Cupcake001_Cupcake_0" geometry={nodes.Cupcake001_Cupcake_0.geometry} material={materials.Cupcake} />
            <mesh name="Cupcake001_Outline_0" geometry={nodes.Cupcake001_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Cupcake002" position={[-200.65, 562.329, -33.941]} rotation={[-1.731, 0.229, 0.386]} scale={100}>
            <mesh name="Cupcake002_Cupcake_0" geometry={nodes.Cupcake002_Cupcake_0.geometry} material={materials.Cupcake} />
            <mesh name="Cupcake002_Outline_0" geometry={nodes.Cupcake002_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Cupcake003" position={[-200.65, 562.329, -33.941]} rotation={[-1.731, 0.229, 0.386]} scale={100}>
            <mesh name="Cupcake003_Cupcake_0" geometry={nodes.Cupcake003_Cupcake_0.geometry} material={materials.Cupcake} />
            <mesh name="Cupcake003_Outline_0" geometry={nodes.Cupcake003_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Souffle" position={[-219.307, 565.812, -331.98]} rotation={[-1.373, 0.371, -0.153]} scale={100}>
            <mesh name="Souffle_Souffle_0" geometry={nodes.Souffle_Souffle_0.geometry} material={materials.Souffle} />
            <mesh name="Souffle_Outline_0" geometry={nodes.Souffle_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Souffle001" position={[-218.51, 567.82, -331.578]} rotation={[-1.373, 0.371, -0.153]} scale={100}>
            <mesh name="Souffle001_Souffle_0" geometry={nodes.Souffle001_Souffle_0.geometry} material={materials.Souffle} />
            <mesh name="Souffle001_Outline_0" geometry={nodes.Souffle001_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Souffle002" position={[-219.307, 565.812, -331.98]} rotation={[-1.373, 0.371, -0.153]} scale={100}>
            <mesh name="Souffle002_Souffle_0" geometry={nodes.Souffle002_Souffle_0.geometry} material={materials.Souffle} />
            <mesh name="Souffle002_Outline_0" geometry={nodes.Souffle002_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Souffle003" position={[-214.463, 566.843, -334.673]} rotation={[-1.373, 0.371, -0.153]} scale={100}>
            <mesh name="Souffle003_Souffle_0" geometry={nodes.Souffle003_Souffle_0.geometry} material={materials.Souffle} />
            <mesh name="Souffle003_Outline_0" geometry={nodes.Souffle003_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Cake_orange" position={[-175.922, 593.195, -622.336]} rotation={[-1.531, 0.209, -0.12]} scale={100}>
            <mesh name="Cake_orange_Cake_orange_0" geometry={nodes.Cake_orange_Cake_orange_0.geometry} material={materials.Cake_orange} />
            <mesh name="Cake_orange_Outline_0" geometry={nodes.Cake_orange_Outline_0.geometry} material={materials.Outline} />
          </group>
          <group name="Cake_orange001" position={[-161.25, 617.682, -619.163]} rotation={[-1.531, 0.209, -0.12]} scale={100}>
            <mesh name="Cake_orange001_Cake_orange_0" geometry={nodes.Cake_orange001_Cake_orange_0.geometry} material={materials.Cake_orange} />
            <mesh name="Cake_orange001_Outline_0" geometry={nodes.Cake_orange001_Outline_0.geometry} material={materials.Outline} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cute_pastries-transformed.glb')
